import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>
          <Link href="/">A Blog about Music</Link>
        </h1>
        <hr />
        {children}
      </body>
    </html>
  );
}
